### ISSUE TITLE
Error: Couldn't install: openerp-bootstrap 1.0b2

### ISSUE THREAD

**Issue by max3903** [simahawk/openerp_bootstrap#1]
Hello,

I tried to install OpenERP using the buildout recipe which includes openerp_bootstrap.

Unfortunately, I got:

[...]
Getting distribution for 'openerp-bootstrap'.
error: HISTORY.txt: No such file or directory
An error occurred when trying to install openerp-bootstrap 1.0b2. Look above this message for any errors that were output by easy_install.
While:
  Installing paste.
  Getting distribution for 'openerp-bootstrap'.
Error: Couldn't install: openerp-bootstrap 1.0b2

**Comment by max3903** [comment]
Here is the content of my build/openerp-bootstrap directory :

$ ls -lh build/openerp-bootstrap/
total 60K
drwxrwxr-x 2 max max 4,0K déc  4 11:48 openerp_bootstrap
drwxrwxr-x 2 max max 4,0K déc  4 11:48 openerp_bootstrap.egg-info
drwxrwxr-x 2 max max 4,0K déc  4 11:48 pip-egg-info
-rw-rw-r-- 1 max max 2,6K déc  4 11:48 PKG-INFO
-rw-rw-r-- 1 max max  820 déc  4 11:48 README.rst
-rw-rw-r-- 1 max max   59 déc  4 11:48 setup.cfg
-rw-rw-r-- 1 max max 1,2K déc  4 11:48 setup.py

**Comment by yajo** [comment]
I'm also affected.

Quick fix: `touch HISTORY.txt`

**Comment by jcmendozav** [comment]
Hello

I have the same Issue ... 

$ sudo pip install openerp_bootstrap
Downloading/unpacking openerp-bootstrap
  Downloading openerp_bootstrap-1.0b2.zip
  Running setup.py egg_info for package openerp-bootstrap
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/jcmendoza/build/openerp-bootstrap/setup.py", line 13, in <module>
        long_description=get_long_desc(),
      File "/home/jcmendoza/build/openerp-bootstrap/setup.py", line 8, in get_long_desc
        return '\n\n'.join([open(x).read() for x in toread])
    IOError: [Errno 2] No such file or directory: 'HISTORY.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/jcmendoza/build/openerp-bootstrap/setup.py", line 13, in <module>

```
long_description=get_long_desc(),
```

  File "/home/jcmendoza/build/openerp-bootstrap/setup.py", line 8, in get_long_desc

```
return '\n\n'.join([open(x).read() for x in toread])
```

IOError: [Errno 2] No such file or directory: 'HISTORY.txt'

---

Command python setup.py egg_info failed with error code 1

**Comment by tartavull** [comment]
sudo pip install openerp_bootstrap
Downloading/unpacking openerp-bootstrap
  Running setup.py egg_info for package openerp-bootstrap
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/ai/build/openerp-bootstrap/setup.py", line 13, in <module>
        long_description=get_long_desc(),
      File "/home/ai/build/openerp-bootstrap/setup.py", line 8, in get_long_desc
        return '\n\n'.join([open(x).read() for x in toread])
    IOError: [Errno 2] No such file or directory: 'HISTORY.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/ai/build/openerp-bootstrap/setup.py", line 13, in <module>

```
long_description=get_long_desc(),
```

  File "/home/ai/build/openerp-bootstrap/setup.py", line 8, in get_long_desc

```
return '\n\n'.join([open(x).read() for x in toread])
```

IOError: [Errno 2] No such file or directory: 'HISTORY.txt'

---

Command python setup.py egg_info failed with error code 1
Storing complete log in /home/ai/.pip/pip.log

**Comment by tartavull** [comment]
You can do:
git clone https://github.com/simahawk/openerp_bootstrap.git
sudo python setup.py install

to install the package

**Comment by max3903** [comment]
If I understand well, the issue is fixed, but the package needs to be updated on https://pypi.python.org/pypi/openerp_bootstrap/. 

Am I correct ?

**Comment by tartavull** [comment]
Yes you are

**Comment by simahawk** [comment]
holy crap! sorry guys, I was missing notifications from this repo somewhat :(
Indeed, it looks like the HISTORY file is there but is not taken into account by the packaging machinery.
I'll add a manifest.
Thanks for pointing out, and sorry once again for not hearing your voices :)

**Comment by simahawk** [comment]
Done. Please try https://pypi.python.org/pypi/openerp_bootstrap/1.0b3

**Comment by max3903** [comment]
Works like a charm now.

Thank you!
